name: "my first github action"

on:
  push:
    branches: 
      - 'feature/**'
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  job:
    name: terraform init
    runs-on: mygithub-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print India
        run: echo "I love my India"

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: id-token
