name: "my first github action"

on:
 push:
   branches: 
     - 'feature/**'
     - 'main'
jobs:
 terraforminit:
   name: terraform init
   runs-on: mygithub-runner
   steps:
    - name: india
      run: echo i love my india

    - name: india
      run: echo welcome!

    - name: india
      run: echo most welcome
